namespace IntelliTrack.Client.Application.Reportes
{
  /// <summary>
  /// Summary description for Regadores.
  /// </summary>
  partial class Regadores
  {

    /// <summary>
    /// Clean up any resources being used.
    /// </summary>
    protected override void Dispose(bool disposing)
    {
      if (disposing)
      {
      }
      base.Dispose(disposing);
    }

    #region ActiveReport Designer generated code
    /// <summary>
    /// Required method for Designer support - do not modify
    /// the contents of this method with the code editor.
    /// </summary>
    private void InitializeComponent()
    {
      System.ComponentModel.ComponentResourceManager componentResourceManager = new System.ComponentModel.ComponentResourceManager(typeof(IntelliTrack.Client.Application.Reportes.Regadores));
      DataDynamics.ActiveReports.DataSources.SqlDBDataSource sqlDBDataSource = new DataDynamics.ActiveReports.DataSources.SqlDBDataSource();
      textBox3 = new DataDynamics.ActiveReports.TextBox();
      txtEstado = new DataDynamics.ActiveReports.TextBox();
      txtTiempoCarga1 = new DataDynamics.ActiveReports.TextBox();
      txtTiempoDetenido1 = new DataDynamics.ActiveReports.TextBox();
      txtTiempoTransito1 = new DataDynamics.ActiveReports.TextBox();
      txtDIA_HORA1 = new DataDynamics.ActiveReports.TextBox();
      txtDIA_HORA_Final1 = new DataDynamics.ActiveReports.TextBox();
      txtDistancia = new DataDynamics.ActiveReports.TextBox();
      txtReferenciaSalida1 = new DataDynamics.ActiveReports.TextBox();
      txtReferenciaCaminos1 = new DataDynamics.ActiveReports.TextBox();
      txtReferenciaLlegada1 = new DataDynamics.ActiveReports.TextBox();
      txtVelocidadMaxima1 = new DataDynamics.ActiveReports.TextBox();
      txtVelocidadPromedio1 = new DataDynamics.ActiveReports.TextBox();
      txtIDTransponder1 = new DataDynamics.ActiveReports.TextBox();
      label1 = new DataDynamics.ActiveReports.Label();
      label5 = new DataDynamics.ActiveReports.Label();
      label6 = new DataDynamics.ActiveReports.Label();
      label7 = new DataDynamics.ActiveReports.Label();
      labelDistancia = new DataDynamics.ActiveReports.Label();
      label8 = new DataDynamics.ActiveReports.Label();
      label9 = new DataDynamics.ActiveReports.Label();
      label10 = new DataDynamics.ActiveReports.Label();
      label11 = new DataDynamics.ActiveReports.Label();
      label12 = new DataDynamics.ActiveReports.Label();
      label13 = new DataDynamics.ActiveReports.Label();
      label4 = new DataDynamics.ActiveReports.Label();
      label14 = new DataDynamics.ActiveReports.Label();
      label15 = new DataDynamics.ActiveReports.Label();
      label16 = new DataDynamics.ActiveReports.Label();
      label17 = new DataDynamics.ActiveReports.Label();
      label18 = new DataDynamics.ActiveReports.Label();
      label19 = new DataDynamics.ActiveReports.Label();
      label20 = new DataDynamics.ActiveReports.Label();
      label21 = new DataDynamics.ActiveReports.Label();
      txtFechaDesde1 = new DataDynamics.ActiveReports.TextBox();
      txtFechaHasta1 = new DataDynamics.ActiveReports.TextBox();
      txtVelocidadDesde1 = new DataDynamics.ActiveReports.TextBox();
      txtVelocidadHasta1 = new DataDynamics.ActiveReports.TextBox();
      label22 = new DataDynamics.ActiveReports.Label();
      label23 = new DataDynamics.ActiveReports.Label();
      label24 = new DataDynamics.ActiveReports.Label();
      label25 = new DataDynamics.ActiveReports.Label();
      label27 = new DataDynamics.ActiveReports.Label();
      label28 = new DataDynamics.ActiveReports.Label();
      picture1 = new DataDynamics.ActiveReports.Picture();
      txtTiempoTotalCarga = new DataDynamics.ActiveReports.TextBox();
      txtTempoTotalTransito = new DataDynamics.ActiveReports.TextBox();
      txtTiempoTotalDetenido = new DataDynamics.ActiveReports.TextBox();
      txtIDElemento1 = new DataDynamics.ActiveReports.TextBox();
      pageHeader = new DataDynamics.ActiveReports.PageHeader();
      detail = new DataDynamics.ActiveReports.Detail();
      line1 = new DataDynamics.ActiveReports.Line();
      pageFooter = new DataDynamics.ActiveReports.PageFooter();
      groupHeader1 = new DataDynamics.ActiveReports.GroupHeader();
      shape3 = new DataDynamics.ActiveReports.Shape();
      shape1 = new DataDynamics.ActiveReports.Shape();
      shape2 = new DataDynamics.ActiveReports.Shape();
      groupFooter1 = new DataDynamics.ActiveReports.GroupFooter();
      shape4 = new DataDynamics.ActiveReports.Shape();
      FechaDesde = new DataDynamics.ActiveReports.Parameter();
      FechaHasta = new DataDynamics.ActiveReports.Parameter();
      VelocidadDesde = new DataDynamics.ActiveReports.Parameter();
      VelocidadHasta = new DataDynamics.ActiveReports.Parameter();
      textBox3.BeginInit();
      txtEstado.BeginInit();
      txtTiempoCarga1.BeginInit();
      txtTiempoDetenido1.BeginInit();
      txtTiempoTransito1.BeginInit();
      txtDIA_HORA1.BeginInit();
      txtDIA_HORA_Final1.BeginInit();
      txtDistancia.BeginInit();
      txtReferenciaSalida1.BeginInit();
      txtReferenciaCaminos1.BeginInit();
      txtReferenciaLlegada1.BeginInit();
      txtVelocidadMaxima1.BeginInit();
      txtVelocidadPromedio1.BeginInit();
      txtIDTransponder1.BeginInit();
      label1.BeginInit();
      label5.BeginInit();
      label6.BeginInit();
      label7.BeginInit();
      labelDistancia.BeginInit();
      label8.BeginInit();
      label9.BeginInit();
      label10.BeginInit();
      label11.BeginInit();
      label12.BeginInit();
      label13.BeginInit();
      label4.BeginInit();
      label14.BeginInit();
      label15.BeginInit();
      label16.BeginInit();
      label17.BeginInit();
      label18.BeginInit();
      label19.BeginInit();
      label20.BeginInit();
      label21.BeginInit();
      txtFechaDesde1.BeginInit();
      txtFechaHasta1.BeginInit();
      txtVelocidadDesde1.BeginInit();
      txtVelocidadHasta1.BeginInit();
      label22.BeginInit();
      label23.BeginInit();
      label24.BeginInit();
      label25.BeginInit();
      label27.BeginInit();
      label28.BeginInit();
      //picture1.BeginInit();
      txtTiempoTotalCarga.BeginInit();
      txtTempoTotalTransito.BeginInit();
      txtTiempoTotalDetenido.BeginInit();
      txtIDElemento1.BeginInit();
      BeginInit();
      textBox3.Border.BottomColor = System.Drawing.Color.Black;
      textBox3.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      textBox3.Border.LeftColor = System.Drawing.Color.Black;
      textBox3.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      textBox3.Border.RightColor = System.Drawing.Color.Black;
      textBox3.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      textBox3.Border.TopColor = System.Drawing.Color.Black;
      textBox3.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(textBox3, "textBox3");
      textBox3.DistinctField = null;
      textBox3.Height = 0.1574803F;
      textBox3.Left = 4.448819F;
      textBox3.Name = "textBox3";
      textBox3.OutputFormat = componentResourceManager.GetString("textBox3.OutputFormat");
      textBox3.SummaryGroup = null;
      textBox3.Top = 0.03937008F;
      textBox3.Width = 1.574803F;
      txtEstado.Border.BottomColor = System.Drawing.Color.Black;
      txtEstado.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtEstado.Border.LeftColor = System.Drawing.Color.Black;
      txtEstado.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtEstado.Border.RightColor = System.Drawing.Color.Black;
      txtEstado.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtEstado.Border.TopColor = System.Drawing.Color.Black;
      txtEstado.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtEstado, "txtEstado");
      txtEstado.DataField = "Estado";
      txtEstado.DistinctField = null;
      txtEstado.Height = 0.1968504F;
      txtEstado.Left = 0.8125F;
      txtEstado.Name = "txtEstado";
      txtEstado.OutputFormat = componentResourceManager.GetString("txtEstado.OutputFormat");
      txtEstado.SummaryGroup = null;
      txtEstado.Top = 0.0F;
      txtEstado.Width = 0.6692914F;
      txtTiempoCarga1.Border.BottomColor = System.Drawing.Color.Black;
      txtTiempoCarga1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTiempoCarga1.Border.LeftColor = System.Drawing.Color.Black;
      txtTiempoCarga1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTiempoCarga1.Border.RightColor = System.Drawing.Color.Black;
      txtTiempoCarga1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTiempoCarga1.Border.TopColor = System.Drawing.Color.Black;
      txtTiempoCarga1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtTiempoCarga1, "txtTiempoCarga1");
      txtTiempoCarga1.DataField = "TiempoCarga";
      txtTiempoCarga1.DistinctField = null;
      txtTiempoCarga1.Height = 0.1968504F;
      txtTiempoCarga1.Left = 0.07874016F;
      txtTiempoCarga1.MultiLine = false;
      txtTiempoCarga1.Name = "txtTiempoCarga1";
      txtTiempoCarga1.SummaryGroup = null;
      txtTiempoCarga1.Top = 0.0F;
      txtTiempoCarga1.Width = 0.6496063F;
      txtTiempoDetenido1.Border.BottomColor = System.Drawing.Color.Black;
      txtTiempoDetenido1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTiempoDetenido1.Border.LeftColor = System.Drawing.Color.Black;
      txtTiempoDetenido1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTiempoDetenido1.Border.RightColor = System.Drawing.Color.Black;
      txtTiempoDetenido1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTiempoDetenido1.Border.TopColor = System.Drawing.Color.Black;
      txtTiempoDetenido1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtTiempoDetenido1, "txtTiempoDetenido1");
      txtTiempoDetenido1.DataField = "TiempoDetenido";
      txtTiempoDetenido1.DistinctField = null;
      txtTiempoDetenido1.Height = 0.1968504F;
      txtTiempoDetenido1.Left = 0.07874018F;
      txtTiempoDetenido1.Name = "txtTiempoDetenido1";
      txtTiempoDetenido1.SummaryGroup = null;
      txtTiempoDetenido1.Top = 0.0F;
      txtTiempoDetenido1.Width = 0.6496063F;
      txtTiempoTransito1.Border.BottomColor = System.Drawing.Color.Black;
      txtTiempoTransito1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTiempoTransito1.Border.LeftColor = System.Drawing.Color.Black;
      txtTiempoTransito1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTiempoTransito1.Border.RightColor = System.Drawing.Color.Black;
      txtTiempoTransito1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTiempoTransito1.Border.TopColor = System.Drawing.Color.Black;
      txtTiempoTransito1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtTiempoTransito1, "txtTiempoTransito1");
      txtTiempoTransito1.DataField = "TiempoTransito";
      txtTiempoTransito1.DistinctField = null;
      txtTiempoTransito1.Height = 0.1968504F;
      txtTiempoTransito1.Left = 0.07874012F;
      txtTiempoTransito1.Name = "txtTiempoTransito1";
      txtTiempoTransito1.SummaryGroup = null;
      txtTiempoTransito1.Top = 0.0F;
      txtTiempoTransito1.Width = 0.6496063F;
      txtDIA_HORA1.Border.BottomColor = System.Drawing.Color.Black;
      txtDIA_HORA1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtDIA_HORA1.Border.LeftColor = System.Drawing.Color.Black;
      txtDIA_HORA1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtDIA_HORA1.Border.RightColor = System.Drawing.Color.Black;
      txtDIA_HORA1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtDIA_HORA1.Border.TopColor = System.Drawing.Color.Black;
      txtDIA_HORA1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtDIA_HORA1, "txtDIA_HORA1");
      txtDIA_HORA1.DataField = "DIA_HORA";
      txtDIA_HORA1.DistinctField = null;
      txtDIA_HORA1.Height = 0.1968504F;
      txtDIA_HORA1.Left = 1.5625F;
      txtDIA_HORA1.Name = "txtDIA_HORA1";
      txtDIA_HORA1.SummaryGroup = null;
      txtDIA_HORA1.Top = 0.0F;
      txtDIA_HORA1.Width = 0.6692914F;
      txtDIA_HORA_Final1.Border.BottomColor = System.Drawing.Color.Black;
      txtDIA_HORA_Final1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtDIA_HORA_Final1.Border.LeftColor = System.Drawing.Color.Black;
      txtDIA_HORA_Final1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtDIA_HORA_Final1.Border.RightColor = System.Drawing.Color.Black;
      txtDIA_HORA_Final1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtDIA_HORA_Final1.Border.TopColor = System.Drawing.Color.Black;
      txtDIA_HORA_Final1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtDIA_HORA_Final1, "txtDIA_HORA_Final1");
      txtDIA_HORA_Final1.DataField = "DIA_HORA_Final";
      txtDIA_HORA_Final1.DistinctField = null;
      txtDIA_HORA_Final1.Height = 0.2F;
     txtDIA_HORA_Final1.Left = 2.1875F;
      txtDIA_HORA_Final1.Name = "txtDIA_HORA_Final1";
      txtDIA_HORA_Final1.SummaryGroup = null;
      txtDIA_HORA_Final1.Top = 0.0F;
      txtDIA_HORA_Final1.Width = 0.6692914F;

      txtDistancia.DataField = "DistanciaRecorrida";
      txtDistancia.Border.BottomColor = System.Drawing.Color.Black;
      txtDistancia.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtDistancia.Border.LeftColor = System.Drawing.Color.Black;
      txtDistancia.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtDistancia.Border.RightColor = System.Drawing.Color.Black;
      txtDistancia.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtDistancia.Border.TopColor = System.Drawing.Color.Black;
      txtDistancia.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtDistancia, "txtDistancia");
      txtDistancia.DataField = "DistanciaRecorrida";
      txtDistancia.DistinctField = null;
      txtDistancia.Height = 0.2F;
      txtDistancia.Left = 2.9375F;
      txtDistancia.Name = "txtDistancia";
      txtDistancia.SummaryGroup = null;
      txtDistancia.Top = 0.0F;
      txtDistancia.Width = 0.6692914F;
      txtDistancia.OutputFormat = "#,##0.00";

      txtReferenciaSalida1.Border.BottomColor = System.Drawing.Color.Black;
      txtReferenciaSalida1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtReferenciaSalida1.Border.LeftColor = System.Drawing.Color.Black;
      txtReferenciaSalida1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtReferenciaSalida1.Border.RightColor = System.Drawing.Color.Black;
      txtReferenciaSalida1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtReferenciaSalida1.Border.TopColor = System.Drawing.Color.Black;
      txtReferenciaSalida1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtReferenciaSalida1, "txtReferenciaSalida1");
      txtReferenciaSalida1.DataField = "ReferenciaSalida";
      txtReferenciaSalida1.DistinctField = null;
      txtReferenciaSalida1.Height = 0.1968504F;
      //txtReferenciaSalida1.Left = 2.9375F + txtDistancia.Width;
      txtReferenciaSalida1.Left = 2.9375F + 1.0649606F;
      txtReferenciaSalida1.Name = "txtReferenciaSalida1";
      txtReferenciaSalida1.OutputFormat = componentResourceManager.GetString("txtReferenciaSalida1.OutputFormat");
      txtReferenciaSalida1.SummaryGroup = null;
      txtReferenciaSalida1.Top = 0.0F;
      txtReferenciaSalida1.Width = 0.984252F;
      txtReferenciaCaminos1.Border.BottomColor = System.Drawing.Color.Black;
      txtReferenciaCaminos1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtReferenciaCaminos1.Border.LeftColor = System.Drawing.Color.Black;
      txtReferenciaCaminos1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtReferenciaCaminos1.Border.RightColor = System.Drawing.Color.Black;
      txtReferenciaCaminos1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtReferenciaCaminos1.Border.TopColor = System.Drawing.Color.Black;
      txtReferenciaCaminos1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtReferenciaCaminos1, "txtReferenciaCaminos1");
      txtReferenciaCaminos1.DataField = "ReferenciaCaminos";
      txtReferenciaCaminos1.DistinctField = null;
      txtReferenciaCaminos1.Height = 0.1875F;
      //txtReferenciaCaminos1.Left = 3.9375F;
      txtReferenciaCaminos1.Left = 3.9375F + 1.0649606F;
      txtReferenciaCaminos1.Name = "txtReferenciaCaminos1";
      txtReferenciaCaminos1.OutputFormat = componentResourceManager.GetString("txtReferenciaCaminos1.OutputFormat");
      txtReferenciaCaminos1.SummaryGroup = null;
      txtReferenciaCaminos1.Top = 0.0F;
      txtReferenciaCaminos1.Width = 4.0F;
      txtReferenciaLlegada1.Border.BottomColor = System.Drawing.Color.Black;
      txtReferenciaLlegada1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtReferenciaLlegada1.Border.LeftColor = System.Drawing.Color.Black;
      txtReferenciaLlegada1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtReferenciaLlegada1.Border.RightColor = System.Drawing.Color.Black;
      txtReferenciaLlegada1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtReferenciaLlegada1.Border.TopColor = System.Drawing.Color.Black;
      txtReferenciaLlegada1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtReferenciaLlegada1, "txtReferenciaLlegada1");
      txtReferenciaLlegada1.DataField = "ReferenciaLlegada";
      txtReferenciaLlegada1.DistinctField = null;
      txtReferenciaLlegada1.Height = 0.2F;
      txtReferenciaLlegada1.Left = 8.0F;
      txtReferenciaLlegada1.Name = "txtReferenciaLlegada1";
      txtReferenciaLlegada1.OutputFormat = componentResourceManager.GetString("txtReferenciaLlegada1.OutputFormat");
      txtReferenciaLlegada1.SummaryGroup = null;
      txtReferenciaLlegada1.Top = 0.0F;
      txtReferenciaLlegada1.Width = 0.984252F - txtDistancia.Width;
      txtVelocidadMaxima1.Border.BottomColor = System.Drawing.Color.Black;
      txtVelocidadMaxima1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtVelocidadMaxima1.Border.LeftColor = System.Drawing.Color.Black;
      txtVelocidadMaxima1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtVelocidadMaxima1.Border.RightColor = System.Drawing.Color.Black;
      txtVelocidadMaxima1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtVelocidadMaxima1.Border.TopColor = System.Drawing.Color.Black;
      txtVelocidadMaxima1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtVelocidadMaxima1, "txtVelocidadMaxima1");
      txtVelocidadMaxima1.DataField = "VelocidadMaxima";
      txtVelocidadMaxima1.DistinctField = null;
      txtVelocidadMaxima1.Height = 0.2F;
      txtVelocidadMaxima1.Left = 8.9375F;
      txtVelocidadMaxima1.Name = "txtVelocidadMaxima1";
      txtVelocidadMaxima1.OutputFormat = componentResourceManager.GetString("txtVelocidadMaxima1.OutputFormat");
      txtVelocidadMaxima1.SummaryGroup = null;
      txtVelocidadMaxima1.Top = 0.0F;
      txtVelocidadMaxima1.Width = 0.6692914F;
      txtVelocidadPromedio1.Border.BottomColor = System.Drawing.Color.Black;
      txtVelocidadPromedio1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtVelocidadPromedio1.Border.LeftColor = System.Drawing.Color.Black;
      txtVelocidadPromedio1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtVelocidadPromedio1.Border.RightColor = System.Drawing.Color.Black;
      txtVelocidadPromedio1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtVelocidadPromedio1.Border.TopColor = System.Drawing.Color.Black;
      txtVelocidadPromedio1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtVelocidadPromedio1, "txtVelocidadPromedio1");
      txtVelocidadPromedio1.DataField = "VelocidadPromedio";
      txtVelocidadPromedio1.DistinctField = null;
      txtVelocidadPromedio1.Height = 0.2F;
      txtVelocidadPromedio1.Left = 9.6875F;
      txtVelocidadPromedio1.Name = "txtVelocidadPromedio1";
      txtVelocidadPromedio1.OutputFormat = componentResourceManager.GetString("txtVelocidadPromedio1.OutputFormat");
      txtVelocidadPromedio1.SummaryGroup = null;
      txtVelocidadPromedio1.Top = 0.0F;
      txtVelocidadPromedio1.Width = 0.6692914F;
      txtIDTransponder1.Border.BottomColor = System.Drawing.Color.Black;
      txtIDTransponder1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtIDTransponder1.Border.LeftColor = System.Drawing.Color.Black;
      txtIDTransponder1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtIDTransponder1.Border.RightColor = System.Drawing.Color.Black;
      txtIDTransponder1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtIDTransponder1.Border.TopColor = System.Drawing.Color.Black;
      txtIDTransponder1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtIDTransponder1, "txtIDTransponder1");
      txtIDTransponder1.DataField = "IDTransponder";
      txtIDTransponder1.DistinctField = null;
      txtIDTransponder1.Height = 0.1574803F;
      txtIDTransponder1.Left = 3.937008F;
      txtIDTransponder1.Name = "txtIDTransponder1";
      txtIDTransponder1.OutputFormat = componentResourceManager.GetString("txtIDTransponder1.OutputFormat");
      txtIDTransponder1.SummaryGroup = null;
      txtIDTransponder1.Top = 0.511811F;
      txtIDTransponder1.Width = 1.0F;
      label1.Border.BottomColor = System.Drawing.Color.Black;
      label1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label1.Border.LeftColor = System.Drawing.Color.Black;
      label1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label1.Border.RightColor = System.Drawing.Color.Black;
      label1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label1.Border.TopColor = System.Drawing.Color.Black;
      label1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label1, "label1");
      label1.Height = 0.1722441F;
      label1.HyperLink = null;
      label1.Left = 0.07874016F;
      label1.Name = "label1";
      label1.Top = 1.023622F;
      label1.Width = 0.6692914F;
      label5.Border.BottomColor = System.Drawing.Color.Black;
      label5.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label5.Border.LeftColor = System.Drawing.Color.Black;
      label5.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label5.Border.RightColor = System.Drawing.Color.Black;
      label5.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label5.Border.TopColor = System.Drawing.Color.Black;
      label5.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label5, "label5");
      label5.Height = 0.1722441F;
      label5.HyperLink = null;
      label5.Left = 0.8125F;
      label5.Name = "label5";
      label5.Top = 1.023622F;
      label5.Width = 0.6692914F;
      label6.Border.BottomColor = System.Drawing.Color.Black;
      label6.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label6.Border.LeftColor = System.Drawing.Color.Black;
      label6.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label6.Border.RightColor = System.Drawing.Color.Black;
      label6.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label6.Border.TopColor = System.Drawing.Color.Black;
      label6.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label6, "label6");
      label6.Height = 0.1722441F;
      label6.HyperLink = null;
      label6.Left = 1.5625F;
      label6.Name = "label6";
      label6.Top = 1.023622F;
      label6.Width = 0.6692914F;
      label7.Border.BottomColor = System.Drawing.Color.Black;
      label7.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label7.Border.LeftColor = System.Drawing.Color.Black;
      label7.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label7.Border.RightColor = System.Drawing.Color.Black;
      label7.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label7.Border.TopColor = System.Drawing.Color.Black;
      label7.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label7, "label7");
      label7.Height = 0.1722441F;
      label7.HyperLink = null;
      label7.Left = 2.1875F;
      label7.Name = "label7";
      label7.Top = 1.023622F;
      label7.Width = 0.6692914F;

      labelDistancia.Border.BottomColor = System.Drawing.Color.Black;
      labelDistancia.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      labelDistancia.Border.LeftColor = System.Drawing.Color.Black;
      labelDistancia.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      labelDistancia.Border.RightColor = System.Drawing.Color.Black;
      labelDistancia.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      labelDistancia.Border.TopColor = System.Drawing.Color.Black;
      labelDistancia.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(labelDistancia, "labelDistancia");
      labelDistancia.Height = 0.1722441F;
      labelDistancia.HyperLink = null;
      labelDistancia.Left = 2.9375F;
      labelDistancia.Name = "labelDistancia";
      labelDistancia.Top = 1.023622F;
      labelDistancia.Width = 0.984252F;


      label8.Border.BottomColor = System.Drawing.Color.Black;
      label8.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label8.Border.LeftColor = System.Drawing.Color.Black;
      label8.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label8.Border.RightColor = System.Drawing.Color.Black;
      label8.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label8.Border.TopColor = System.Drawing.Color.Black;
      label8.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label8, "label8");
      label8.Height = 0.1722441F;
      label8.HyperLink = null;
      label8.Left = 2.9375F + 1.0649606F;
      label8.Name = "label8";
      label8.Top = 1.023622F;
      label8.Width = 0.984252F;

      

      label9.Border.BottomColor = System.Drawing.Color.Black;
      label9.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label9.Border.LeftColor = System.Drawing.Color.Black;
      label9.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label9.Border.RightColor = System.Drawing.Color.Black;
      label9.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label9.Border.TopColor = System.Drawing.Color.Black;
      label9.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label9, "label9");
      label9.Height = 0.1574803F;
      label9.HyperLink = null;
      label9.Left = 3.149606F;
      label9.Name = "label9";
      label9.Top = 0.511811F;
      label9.Width = 0.7874016F;
      label10.Border.BottomColor = System.Drawing.Color.Black;
      label10.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label10.Border.LeftColor = System.Drawing.Color.Black;
      label10.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label10.Border.RightColor = System.Drawing.Color.Black;
      label10.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label10.Border.TopColor = System.Drawing.Color.Black;
      label10.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label10, "label10");
      label10.Height = 0.1875F;
      label10.HyperLink = null;
      label10.Left = 3.9375F + 1.0649606F;
      label10.Name = "label10";
      label10.Top = 1.023622F;
      label10.Width = 4.0F - 1.0649606F;
      label11.Border.BottomColor = System.Drawing.Color.Black;
      label11.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label11.Border.LeftColor = System.Drawing.Color.Black;
      label11.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label11.Border.RightColor = System.Drawing.Color.Black;
      label11.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label11.Border.TopColor = System.Drawing.Color.Black;
      label11.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label11, "label11");
      label11.Height = 0.1722441F;
      label11.HyperLink = null;
      label11.Left = 8.0F;
      label11.Name = "label11";
      label11.Top = 1.023622F;
      label11.Width = 0.984252F;
      label12.Border.BottomColor = System.Drawing.Color.Black;
      label12.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label12.Border.LeftColor = System.Drawing.Color.Black;
      label12.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label12.Border.RightColor = System.Drawing.Color.Black;
      label12.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label12.Border.TopColor = System.Drawing.Color.Black;
      label12.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label12, "label12");
      label12.Height = 0.1722441F;
      label12.HyperLink = null;
      label12.Left = 8.9375F;
      label12.Name = "label12";
      label12.Top = 1.023622F;
      label12.Width = 0.6692914F;
      label13.Border.BottomColor = System.Drawing.Color.Black;
      label13.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label13.Border.LeftColor = System.Drawing.Color.Black;
      label13.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label13.Border.RightColor = System.Drawing.Color.Black;
      label13.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label13.Border.TopColor = System.Drawing.Color.Black;
      label13.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label13, "label13");
      label13.Height = 0.1722441F;
      label13.HyperLink = null;
      label13.Left = 9.6875F;
      label13.Name = "label13";
      label13.Top = 1.023622F;
      label13.Width = 0.6692914F;
      label4.Border.BottomColor = System.Drawing.Color.Black;
      label4.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label4.Border.LeftColor = System.Drawing.Color.Black;
      label4.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label4.Border.RightColor = System.Drawing.Color.Black;
      label4.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label4.Border.TopColor = System.Drawing.Color.Black;
      label4.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label4, "label4");
      label4.Height = 0.1574803F;
      label4.HyperLink = null;
      label4.Left = 0.07874016F;
      label4.Name = "label4";
      label4.Top = 0.07874016F;
      label4.Width = 2.283465F;
      label14.Border.BottomColor = System.Drawing.Color.Black;
      label14.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label14.Border.LeftColor = System.Drawing.Color.Black;
      label14.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label14.Border.RightColor = System.Drawing.Color.Black;
      label14.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label14.Border.TopColor = System.Drawing.Color.Black;
      label14.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label14, "label14");
      label14.Height = 0.1574803F;
      label14.HyperLink = null;
      label14.Left = 0.07874016F;
      label14.Name = "label14";
      label14.Top = 0.2362205F;
      label14.Width = 1.0F;
      label15.Border.BottomColor = System.Drawing.Color.Black;
      label15.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label15.Border.LeftColor = System.Drawing.Color.Black;
      label15.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label15.Border.RightColor = System.Drawing.Color.Black;
      label15.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label15.Border.TopColor = System.Drawing.Color.Black;
      label15.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label15, "label15");
      label15.Height = 0.1574803F;
      label15.HyperLink = null;
      label15.Left = 0.07874016F;
      label15.Name = "label15";
      label15.Top = 0.3937008F;
      label15.Width = 1.0F;
      label16.Border.BottomColor = System.Drawing.Color.Black;
      label16.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label16.Border.LeftColor = System.Drawing.Color.Black;
      label16.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label16.Border.RightColor = System.Drawing.Color.Black;
      label16.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label16.Border.TopColor = System.Drawing.Color.Black;
      label16.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label16, "label16");
      label16.Height = 0.1574803F;
      label16.HyperLink = null;
      label16.Left = 0.07874016F;
      label16.Name = "label16";
      label16.Top = 0.5511811F;
      label16.Width = 1.0F;
      label17.Border.BottomColor = System.Drawing.Color.Black;
      label17.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label17.Border.LeftColor = System.Drawing.Color.Black;
      label17.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label17.Border.RightColor = System.Drawing.Color.Black;
      label17.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label17.Border.TopColor = System.Drawing.Color.Black;
      label17.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label17, "label17");
      label17.Height = 0.1574803F;
      label17.HyperLink = null;
      label17.Left = 5.314961F;
      label17.Name = "label17";
      label17.Top = 0.3937008F;
      label17.Width = 1.0F;
      label18.Border.BottomColor = System.Drawing.Color.Black;
      label18.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label18.Border.LeftColor = System.Drawing.Color.Black;
      label18.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label18.Border.RightColor = System.Drawing.Color.Black;
      label18.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label18.Border.TopColor = System.Drawing.Color.Black;
      label18.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label18, "label18");
      label18.Height = 0.1574803F;
      label18.HyperLink = null;
      label18.Left = 5.314961F;
      label18.Name = "label18";
      label18.Top = 0.2362205F;
      label18.Width = 1.0F;
      label19.Border.BottomColor = System.Drawing.Color.Black;
      label19.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label19.Border.LeftColor = System.Drawing.Color.Black;
      label19.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label19.Border.RightColor = System.Drawing.Color.Black;
      label19.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label19.Border.TopColor = System.Drawing.Color.Black;
      label19.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label19, "label19");
      label19.Height = 0.1574803F;
      label19.HyperLink = null;
      label19.Left = 8.0625F;
      label19.Name = "label19";
      label19.Top = 0.25F;
      label19.Width = 0.3937005F;
      label20.Border.BottomColor = System.Drawing.Color.Black;
      label20.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label20.Border.LeftColor = System.Drawing.Color.Black;
      label20.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label20.Border.RightColor = System.Drawing.Color.Black;
      label20.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label20.Border.TopColor = System.Drawing.Color.Black;
      label20.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label20, "label20");
      label20.Height = 0.1574803F;
      label20.HyperLink = null;
      label20.Left = 5.314961F;
      label20.Name = "label20";
      label20.Top = 0.07874016F;
      label20.Width = 2.283465F;
      label21.Border.BottomColor = System.Drawing.Color.Black;
      label21.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label21.Border.LeftColor = System.Drawing.Color.Black;
      label21.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label21.Border.RightColor = System.Drawing.Color.Black;
      label21.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label21.Border.TopColor = System.Drawing.Color.Black;
      label21.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label21, "label21");
      label21.Height = 0.1574803F;
      label21.HyperLink = null;
      label21.Left = 8.0625F;
      label21.Name = "label21";
      label21.Top = 0.375F;
      label21.Width = 0.1181104F;
      txtFechaDesde1.Border.BottomColor = System.Drawing.Color.Black;
      txtFechaDesde1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtFechaDesde1.Border.LeftColor = System.Drawing.Color.Black;
      txtFechaDesde1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtFechaDesde1.Border.RightColor = System.Drawing.Color.Black;
      txtFechaDesde1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtFechaDesde1.Border.TopColor = System.Drawing.Color.Black;
      txtFechaDesde1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtFechaDesde1, "txtFechaDesde1");
      txtFechaDesde1.DataField = "param:FechaDesde";
      txtFechaDesde1.DistinctField = null;
      txtFechaDesde1.Height = 0.125F;
      txtFechaDesde1.Left = 6.375F;
      txtFechaDesde1.Name = "txtFechaDesde1";
      txtFechaDesde1.OutputFormat = componentResourceManager.GetString("txtFechaDesde1.OutputFormat");
      txtFechaDesde1.SummaryGroup = null;
      txtFechaDesde1.Top = 0.25F;
      txtFechaDesde1.Width = 1.625F;
      txtFechaHasta1.Border.BottomColor = System.Drawing.Color.Black;
      txtFechaHasta1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtFechaHasta1.Border.LeftColor = System.Drawing.Color.Black;
      txtFechaHasta1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtFechaHasta1.Border.RightColor = System.Drawing.Color.Black;
      txtFechaHasta1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtFechaHasta1.Border.TopColor = System.Drawing.Color.Black;
      txtFechaHasta1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtFechaHasta1, "txtFechaHasta1");
      txtFechaHasta1.DataField = "param:FechaHasta";
      txtFechaHasta1.DistinctField = null;
      txtFechaHasta1.Height = 0.1875F;
      txtFechaHasta1.Left = 8.5F;
      txtFechaHasta1.Name = "txtFechaHasta1";
      txtFechaHasta1.OutputFormat = componentResourceManager.GetString("txtFechaHasta1.OutputFormat");
      txtFechaHasta1.SummaryGroup = null;
      txtFechaHasta1.Top = 0.25F;
      txtFechaHasta1.Width = 1.625F;
      txtVelocidadDesde1.Border.BottomColor = System.Drawing.Color.Black;
      txtVelocidadDesde1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtVelocidadDesde1.Border.LeftColor = System.Drawing.Color.Black;
      txtVelocidadDesde1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtVelocidadDesde1.Border.RightColor = System.Drawing.Color.Black;
      txtVelocidadDesde1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtVelocidadDesde1.Border.TopColor = System.Drawing.Color.Black;
      txtVelocidadDesde1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtVelocidadDesde1, "txtVelocidadDesde1");
      txtVelocidadDesde1.DataField = "param:VelocidadDesde";
      txtVelocidadDesde1.DistinctField = null;
      txtVelocidadDesde1.Height = 0.1574803F;
      txtVelocidadDesde1.Left = 6.377953F;
      txtVelocidadDesde1.Name = "txtVelocidadDesde1";
      txtVelocidadDesde1.OutputFormat = componentResourceManager.GetString("txtVelocidadDesde1.OutputFormat");
      txtVelocidadDesde1.SummaryGroup = null;
      txtVelocidadDesde1.Top = 0.3937008F;
      txtVelocidadDesde1.Width = 1.0F;
      txtVelocidadHasta1.Border.BottomColor = System.Drawing.Color.Black;
      txtVelocidadHasta1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtVelocidadHasta1.Border.LeftColor = System.Drawing.Color.Black;
      txtVelocidadHasta1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtVelocidadHasta1.Border.RightColor = System.Drawing.Color.Black;
      txtVelocidadHasta1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtVelocidadHasta1.Border.TopColor = System.Drawing.Color.Black;
      txtVelocidadHasta1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtVelocidadHasta1, "txtVelocidadHasta1");
      txtVelocidadHasta1.DataField = "param:VelocidadHasta";
      txtVelocidadHasta1.DistinctField = null;
      txtVelocidadHasta1.Height = 0.1574803F;
      txtVelocidadHasta1.Left = 8.5F;
      txtVelocidadHasta1.Name = "txtVelocidadHasta1";
      txtVelocidadHasta1.OutputFormat = componentResourceManager.GetString("txtVelocidadHasta1.OutputFormat");
      txtVelocidadHasta1.SummaryGroup = null;
      txtVelocidadHasta1.Top = 0.375F;
      txtVelocidadHasta1.Width = 1.0F;
      label22.Border.BottomColor = System.Drawing.Color.Black;
      label22.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label22.Border.LeftColor = System.Drawing.Color.Black;
      label22.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label22.Border.RightColor = System.Drawing.Color.Black;
      label22.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label22.Border.TopColor = System.Drawing.Color.Black;
      label22.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label22, "label22");
      label22.Height = 0.1574803F;
      label22.HyperLink = null;
      label22.Left = 2.401575F;
      label22.Name = "label22";
      label22.Top = 0.1968504F;
      label22.Width = 1.0F;
      label23.Border.BottomColor = System.Drawing.Color.Black;
      label23.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label23.Border.LeftColor = System.Drawing.Color.Black;
      label23.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label23.Border.RightColor = System.Drawing.Color.Black;
      label23.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label23.Border.TopColor = System.Drawing.Color.Black;
      label23.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label23, "label23");
      label23.Height = 0.1574803F;
      label23.HyperLink = null;
      label23.Left = 0.07874016F;
      label23.Name = "label23";
      label23.Top = 0.1968504F;
      label23.Width = 1.0F;
      label24.Border.BottomColor = System.Drawing.Color.Black;
      label24.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label24.Border.LeftColor = System.Drawing.Color.Black;
      label24.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label24.Border.RightColor = System.Drawing.Color.Black;
      label24.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label24.Border.TopColor = System.Drawing.Color.Black;
      label24.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label24, "label24");
      label24.Height = 0.1574803F;
      label24.HyperLink = null;
      label24.Left = 0.07874016F;
      label24.Name = "label24";
      label24.Top = 0.03937008F;
      label24.Width = 2.283465F;
      label25.Border.BottomColor = System.Drawing.Color.Black;
      label25.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label25.Border.LeftColor = System.Drawing.Color.Black;
      label25.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label25.Border.RightColor = System.Drawing.Color.Black;
      label25.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label25.Border.TopColor = System.Drawing.Color.Black;
      label25.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label25, "label25");
      label25.Height = 0.1574803F;
      label25.HyperLink = null;
      label25.Left = 0.07874012F;
      label25.Name = "label25";
      label25.Top = 0.3543307F;
      label25.Width = 1.0F;
      label27.Border.BottomColor = System.Drawing.Color.Black;
      label27.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label27.Border.LeftColor = System.Drawing.Color.Black;
      label27.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label27.Border.RightColor = System.Drawing.Color.Black;
      label27.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label27.Border.TopColor = System.Drawing.Color.Black;
      label27.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label27, "label27");
      label27.Height = 0.1574803F;
      label27.HyperLink = null;
      label27.Left = 8.858268F;
      label27.Name = "label27";
      label27.Top = 0.03937008F;
      label27.Width = 1.496063F;
      label28.Border.BottomColor = System.Drawing.Color.Black;
      label28.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label28.Border.LeftColor = System.Drawing.Color.Black;
      label28.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label28.Border.RightColor = System.Drawing.Color.Black;
      label28.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      label28.Border.TopColor = System.Drawing.Color.Black;
      label28.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(label28, "label28");
      label28.Height = 0.472441F;
      label28.HyperLink = null;
      label28.Left = 8.858268F;
      label28.Name = "label28";
      label28.Top = 0.1968504F;
      label28.Width = 1.496063F;
      picture1.Border.BottomColor = System.Drawing.Color.Black;
      picture1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      picture1.Border.LeftColor = System.Drawing.Color.Black;
      picture1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      picture1.Border.RightColor = System.Drawing.Color.Black;
      picture1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      picture1.Border.TopColor = System.Drawing.Color.Black;
      picture1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(picture1, "picture1");
      picture1.Height = 0.7086614F;
      picture1.Image = (System.Drawing.Image)componentResourceManager.GetObject("picture1.Image");
      picture1.ImageData = (System.IO.Stream)componentResourceManager.GetObject("picture1.ImageData");
      picture1.Left = 8.110236F;
      picture1.LineWeight = 0.0F;
      picture1.Name = "picture1";
      picture1.Top = 0.0F;
      picture1.Width = 0.7086614F;
      txtTiempoTotalCarga.Border.BottomColor = System.Drawing.Color.Black;
      txtTiempoTotalCarga.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTiempoTotalCarga.Border.LeftColor = System.Drawing.Color.Black;
      txtTiempoTotalCarga.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTiempoTotalCarga.Border.RightColor = System.Drawing.Color.Black;
      txtTiempoTotalCarga.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTiempoTotalCarga.Border.TopColor = System.Drawing.Color.Black;
      txtTiempoTotalCarga.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtTiempoTotalCarga, "txtTiempoTotalCarga");
      txtTiempoTotalCarga.DistinctField = null;
      txtTiempoTotalCarga.Height = 0.1574803F;
      txtTiempoTotalCarga.Left = 1.125F;
      txtTiempoTotalCarga.Name = "txtTiempoTotalCarga";
      txtTiempoTotalCarga.OutputFormat = componentResourceManager.GetString("txtTiempoTotalCarga.OutputFormat");
      txtTiempoTotalCarga.SummaryGroup = null;
      txtTiempoTotalCarga.Top = 0.1968504F;
      txtTiempoTotalCarga.Width = 1.0F;
      txtTempoTotalTransito.Border.BottomColor = System.Drawing.Color.Black;
      txtTempoTotalTransito.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTempoTotalTransito.Border.LeftColor = System.Drawing.Color.Black;
      txtTempoTotalTransito.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTempoTotalTransito.Border.RightColor = System.Drawing.Color.Black;
      txtTempoTotalTransito.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTempoTotalTransito.Border.TopColor = System.Drawing.Color.Black;
      txtTempoTotalTransito.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtTempoTotalTransito, "txtTempoTotalTransito");
      txtTempoTotalTransito.DistinctField = null;
      txtTempoTotalTransito.Height = 0.1574803F;
      txtTempoTotalTransito.Left = 1.125F;
      txtTempoTotalTransito.Name = "txtTempoTotalTransito";
      txtTempoTotalTransito.OutputFormat = componentResourceManager.GetString("txtTempoTotalTransito.OutputFormat");
      txtTempoTotalTransito.SummaryGroup = null;
      txtTempoTotalTransito.Top = 0.3543307F;
      txtTempoTotalTransito.Width = 1.0F;
      txtTiempoTotalDetenido.Border.BottomColor = System.Drawing.Color.Black;
      txtTiempoTotalDetenido.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTiempoTotalDetenido.Border.LeftColor = System.Drawing.Color.Black;
      txtTiempoTotalDetenido.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTiempoTotalDetenido.Border.RightColor = System.Drawing.Color.Black;
      txtTiempoTotalDetenido.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtTiempoTotalDetenido.Border.TopColor = System.Drawing.Color.Black;
      txtTiempoTotalDetenido.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtTiempoTotalDetenido, "txtTiempoTotalDetenido");
      txtTiempoTotalDetenido.DistinctField = null;
      txtTiempoTotalDetenido.Height = 0.1574803F;
      txtTiempoTotalDetenido.Left = 3.4375F;
      txtTiempoTotalDetenido.Name = "txtTiempoTotalDetenido";
      txtTiempoTotalDetenido.OutputFormat = componentResourceManager.GetString("txtTiempoTotalDetenido.OutputFormat");
      txtTiempoTotalDetenido.SummaryGroup = null;
      txtTiempoTotalDetenido.Top = 0.1968504F;
      txtTiempoTotalDetenido.Width = 1.0F;
      txtIDElemento1.Border.BottomColor = System.Drawing.Color.Black;
      txtIDElemento1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtIDElemento1.Border.LeftColor = System.Drawing.Color.Black;
      txtIDElemento1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtIDElemento1.Border.RightColor = System.Drawing.Color.Black;
      txtIDElemento1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      txtIDElemento1.Border.TopColor = System.Drawing.Color.Black;
      txtIDElemento1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      componentResourceManager.ApplyResources(txtIDElemento1, "txtIDElemento1");
      txtIDElemento1.DataField = "IDElemento";
      txtIDElemento1.DistinctField = null;
      txtIDElemento1.Height = 0.1574803F;
      txtIDElemento1.Left = 1.125F;
      txtIDElemento1.Name = "txtIDElemento1";
      txtIDElemento1.OutputFormat = componentResourceManager.GetString("txtIDElemento1.OutputFormat");
      txtIDElemento1.Top = 0.5511811F;
      txtIDElemento1.Width = 1.0F;
      DataDynamics.ActiveReports.ARControl[] arcontrolArr1 = new DataDynamics.ActiveReports.ARControl[] { textBox3 };
      pageHeader.Controls.AddRange(arcontrolArr1);
      pageHeader.Height = 0.25F;
      pageHeader.Name = "pageHeader";
      detail.ColumnSpacing = 0.0F;
      DataDynamics.ActiveReports.ARControl[] arcontrolArr2 = new DataDynamics.ActiveReports.ARControl[] {
                                                                                                                txtEstado, 
                                                                                                                txtTiempoCarga1, 
                                                                                                                txtTiempoDetenido1, 
                                                                                                                txtTiempoTransito1, 
                                                                                                                txtDIA_HORA1, 
                                                                                                                txtDIA_HORA_Final1, 
                                                                                                                txtDistancia,
                                                                                                                txtReferenciaSalida1, 
                                                                                                                txtReferenciaCaminos1, 
                                                                                                                txtReferenciaLlegada1, 
                                                                                                                txtVelocidadMaxima1, 
                                                                                                                txtVelocidadPromedio1, 
                                                                                                                line1 };
      detail.Controls.AddRange(arcontrolArr2);
      detail.Height = 0.1979167F;
      detail.Name = "detail";
      detail.Format += new System.EventHandler(detail_Format);
      line1.Border.BottomColor = System.Drawing.Color.Black;
      line1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      line1.Border.LeftColor = System.Drawing.Color.Black;
      line1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      line1.Border.RightColor = System.Drawing.Color.Black;
      line1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      line1.Border.TopColor = System.Drawing.Color.Black;
      line1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      line1.Height = 0.0F;
      line1.Left = 0.07874016F;
      line1.LineWeight = 1.0F;
      line1.Name = "line1";
      line1.Top = 0.1968504F;
      line1.Width = 10.31496F;
      line1.X1 = 0.07874016F;
      line1.X2 = 10.3937F;
      line1.Y1 = 0.1968504F;
      line1.Y2 = 0.1968504F;
      pageFooter.Height = 0.25F;
      pageFooter.Name = "pageFooter";
      DataDynamics.ActiveReports.ARControl[] arcontrolArr3 = new DataDynamics.ActiveReports.ARControl[] {
                                                                                                                shape3, 
                                                                                                                shape1, 
                                                                                                                shape2, 
                                                                                                                txtIDTransponder1, 
                                                                                                                label1, 
                                                                                                                label5, 
                                                                                                                label6, 
                                                                                                                label7, 
                                                                                                                labelDistancia,
                                                                                                                label8, 
                                                                                                                label9, 
                                                                                                                label10, 
                                                                                                                label11, 
                                                                                                                label12, 
                                                                                                                label13, 
                                                                                                                label4, 
                                                                                                                label14, 
                                                                                                                label15, 
                                                                                                                label16, 
                                                                                                                label17, 
                                                                                                                label18, 
                                                                                                                label19, 
                                                                                                                label20, 
                                                                                                                label21, 
                                                                                                                txtFechaDesde1, 
                                                                                                                txtFechaHasta1, 
                                                                                                                txtVelocidadDesde1, 
                                                                                                                txtVelocidadHasta1, 
                                                                                                                txtIDElemento1 };
      groupHeader1.Controls.AddRange(arcontrolArr3);
      groupHeader1.DataField = "IDElemento";
      groupHeader1.Height = 1.229167F;
      groupHeader1.Name = "groupHeader1";
      shape3.Border.BottomColor = System.Drawing.Color.Black;
      shape3.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      shape3.Border.LeftColor = System.Drawing.Color.Black;
      shape3.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      shape3.Border.RightColor = System.Drawing.Color.Black;
      shape3.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      shape3.Border.TopColor = System.Drawing.Color.Black;
      shape3.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      shape3.Height = 0.3958333F;
      shape3.Left = 0.03937008F;
      shape3.Name = "shape3";
      shape3.RoundingRadius = 9.999999F;
      shape3.Top = 0.8267716F;
      shape3.Width = 10.37402F;
      shape1.Border.BottomColor = System.Drawing.Color.Black;
      shape1.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      shape1.Border.LeftColor = System.Drawing.Color.Black;
      shape1.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      shape1.Border.RightColor = System.Drawing.Color.Black;
      shape1.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      shape1.Border.TopColor = System.Drawing.Color.Black;
      shape1.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      shape1.Height = 0.7086614F;
      shape1.Left = 0.03937008F;
      shape1.Name = "shape1";
      shape1.RoundingRadius = 9.999999F;
      shape1.Top = 0.03937008F;
      shape1.Width = 5.157481F;
      shape2.Border.BottomColor = System.Drawing.Color.Black;
      shape2.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      shape2.Border.LeftColor = System.Drawing.Color.Black;
      shape2.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      shape2.Border.RightColor = System.Drawing.Color.Black;
      shape2.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      shape2.Border.TopColor = System.Drawing.Color.Black;
      shape2.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      shape2.Height = 0.7086614F;
      shape2.Left = 5.255906F;
      shape2.Name = "shape2";
      shape2.RoundingRadius = 9.999999F;
      shape2.Top = 0.03937008F;
      shape2.Width = 5.157481F;
      DataDynamics.ActiveReports.ARControl[] arcontrolArr4 = new DataDynamics.ActiveReports.ARControl[] {
                                                                                                                picture1, 
                                                                                                                shape4, 
                                                                                                                label22, 
                                                                                                                label23, 
                                                                                                                label24, 
                                                                                                                label25, 
                                                                                                                label27, 
                                                                                                                label28, 
                                                                                                                txtTiempoTotalCarga, 
                                                                                                                txtTempoTotalTransito, 
                                                                                                                txtTiempoTotalDetenido };
      groupFooter1.Controls.AddRange(arcontrolArr4);
      groupFooter1.Height = 0.7708334F;
      groupFooter1.Name = "groupFooter1";
      groupFooter1.NewPage = DataDynamics.ActiveReports.NewPage.After;
      groupFooter1.Format += new System.EventHandler(groupFooter1_Format);
      shape4.Border.BottomColor = System.Drawing.Color.Black;
      shape4.Border.BottomStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      shape4.Border.LeftColor = System.Drawing.Color.Black;
      shape4.Border.LeftStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      shape4.Border.RightColor = System.Drawing.Color.Black;
      shape4.Border.RightStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      shape4.Border.TopColor = System.Drawing.Color.Black;
      shape4.Border.TopStyle = DataDynamics.ActiveReports.BorderLineStyle.None;
      shape4.Height = 0.7086614F;
      shape4.Left = 0.03937008F;
      shape4.Name = "shape4";
      shape4.RoundingRadius = 9.999999F;
      shape4.Top = 0.0F;
      shape4.Width = 10.3937F;
      FechaDesde.DefaultValue = "";
      FechaDesde.Key = "FechaDesde";
      FechaDesde.Prompt = null;
      FechaDesde.PromptUser = false;
      FechaDesde.QueryCreated = false;
      FechaDesde.Tag = null;
      FechaDesde.Type = DataDynamics.ActiveReports.Parameter.DataType.Date;
      FechaHasta.DefaultValue = "";
      FechaHasta.Key = "FechaHasta";
      FechaHasta.Prompt = null;
      FechaHasta.PromptUser = false;
      FechaHasta.QueryCreated = false;
      FechaHasta.Tag = null;
      FechaHasta.Type = DataDynamics.ActiveReports.Parameter.DataType.Date;
      VelocidadDesde.DefaultValue = "";
      VelocidadDesde.Key = "VelocidadDesde";
      VelocidadDesde.Prompt = null;
      VelocidadDesde.PromptUser = false;
      VelocidadDesde.QueryCreated = false;
      VelocidadDesde.Tag = null;
      VelocidadDesde.Type = DataDynamics.ActiveReports.Parameter.DataType.String;
      VelocidadHasta.DefaultValue = "";
      VelocidadHasta.Key = "VelocidadHasta";
      VelocidadHasta.Prompt = null;
      VelocidadHasta.PromptUser = false;
      VelocidadHasta.QueryCreated = false;
      VelocidadHasta.Tag = null;
      VelocidadHasta.Type = DataDynamics.ActiveReports.Parameter.DataType.String;
      MasterReport = false;
      sqlDBDataSource.ConnectionString = "data source=pc-bhb-02\\sqlexpress;initial catalog=SIG;integrated security=SSPI;persist security info=False";
      sqlDBDataSource.SQL = "Select * from RegadoresView";
      DataSource = sqlDBDataSource;
      PageSettings.DefaultPaperSize = false;
      PageSettings.Margins.Bottom = 0.7874016F;
      PageSettings.Margins.Left = 0.7874016F;
      PageSettings.Margins.Right = 0.7874016F;
      PageSettings.Margins.Top = 0.7874016F;
      PageSettings.Orientation = DataDynamics.ActiveReports.Document.PageOrientation.Landscape;
      PageSettings.PaperHeight = 11.69291F;
      PageSettings.PaperKind = System.Drawing.Printing.PaperKind.A4;
      PageSettings.PaperWidth = 8.267716F;
      Parameters.Add(FechaDesde);
      Parameters.Add(FechaHasta);
      Parameters.Add(VelocidadDesde);
      Parameters.Add(VelocidadHasta);
      PrintWidth = 10.51181F;
      Sections.Add(pageHeader);
      Sections.Add(groupHeader1);
      Sections.Add(detail);
      Sections.Add(groupFooter1);
      Sections.Add(pageFooter);
      StyleSheet.Add(new DDCssLib.StyleSheetRule("font-style: normal; text-decoration: none; font-weight: normal; color: Black; font-size: 9pt; font-family: \"Tahoma\"; ddo-char-set: 204; ", "Normal"));
      StyleSheet.Add(new DDCssLib.StyleSheetRule("font-size: 16pt; font-weight: bold; ddo-char-set: 204; ", "Heading1", "Normal"));
      StyleSheet.Add(new DDCssLib.StyleSheetRule("font-family: Times New Roman; font-size: 14pt; font-weight: bold; font-style: italic; ddo-char-set: 204; ", "Heading2", "Normal"));
      StyleSheet.Add(new DDCssLib.StyleSheetRule("font-size: 13pt; font-weight: bold; ddo-char-set: 204; ", "Heading3", "Normal"));
      textBox3.EndInit();
      txtEstado.EndInit();
      txtTiempoCarga1.EndInit();
      txtTiempoDetenido1.EndInit();
      txtTiempoTransito1.EndInit();
      txtDIA_HORA1.EndInit();
      txtDIA_HORA_Final1.EndInit();
      txtDistancia.EndInit();
      txtReferenciaSalida1.EndInit();
      txtReferenciaCaminos1.EndInit();
      txtReferenciaLlegada1.EndInit();
      txtVelocidadMaxima1.EndInit();
      txtVelocidadPromedio1.EndInit();
      txtIDTransponder1.EndInit();
      label1.EndInit();
      label5.EndInit();
      label6.EndInit();
      label7.EndInit();
      labelDistancia.EndInit();
      label8.EndInit();
      label9.EndInit();
      label10.EndInit();
      label11.EndInit();
      label12.EndInit();
      label13.EndInit();
      label4.EndInit();
      label14.EndInit();
      label15.EndInit();
      label16.EndInit();
      label17.EndInit();
      label18.EndInit();
      label19.EndInit();
      label20.EndInit();
      label21.EndInit();
      txtFechaDesde1.EndInit();
      txtFechaHasta1.EndInit();
      txtVelocidadDesde1.EndInit();
      txtVelocidadHasta1.EndInit();
      label22.EndInit();
      label23.EndInit();
      label24.EndInit();
      label25.EndInit();
      label27.EndInit();
      label28.EndInit();
      //picture1.EndInit();
      txtTiempoTotalCarga.EndInit();
      txtTempoTotalTransito.EndInit();
      txtTiempoTotalDetenido.EndInit();
      txtIDElemento1.EndInit();
      EndInit();
    }
    #endregion



    private DataDynamics.ActiveReports.Detail detail;
    internal DataDynamics.ActiveReports.Parameter FechaDesde;
    internal DataDynamics.ActiveReports.Parameter FechaHasta;
    private DataDynamics.ActiveReports.GroupFooter groupFooter1;
    private DataDynamics.ActiveReports.GroupHeader groupHeader1;
    private DataDynamics.ActiveReports.Label label1;
    private DataDynamics.ActiveReports.Label label10;
    private DataDynamics.ActiveReports.Label label11;
    private DataDynamics.ActiveReports.Label label12;
    private DataDynamics.ActiveReports.Label label13;
    private DataDynamics.ActiveReports.Label label14;
    private DataDynamics.ActiveReports.Label label15;
    private DataDynamics.ActiveReports.Label label16;
    private DataDynamics.ActiveReports.Label label17;
    private DataDynamics.ActiveReports.Label label18;
    private DataDynamics.ActiveReports.Label label19;
    private DataDynamics.ActiveReports.Label label20;
    private DataDynamics.ActiveReports.Label label21;
    private DataDynamics.ActiveReports.Label label22;
    private DataDynamics.ActiveReports.Label label23;
    private DataDynamics.ActiveReports.Label label24;
    private DataDynamics.ActiveReports.Label label25;
    private DataDynamics.ActiveReports.Label label27;
    private DataDynamics.ActiveReports.Label label28;
    private DataDynamics.ActiveReports.Label label4;
    private DataDynamics.ActiveReports.Label label5;
    private DataDynamics.ActiveReports.Label label6;
    private DataDynamics.ActiveReports.Label label7;
    private DataDynamics.ActiveReports.Label labelDistancia;
    private DataDynamics.ActiveReports.Label label8;
    private DataDynamics.ActiveReports.Label label9;
    private DataDynamics.ActiveReports.Line line1;

    private DataDynamics.ActiveReports.PageFooter pageFooter;
    private DataDynamics.ActiveReports.PageHeader pageHeader;
    private DataDynamics.ActiveReports.Picture picture1;
    private DataDynamics.ActiveReports.Shape shape1;
    private DataDynamics.ActiveReports.Shape shape2;
    private DataDynamics.ActiveReports.Shape shape3;
    private DataDynamics.ActiveReports.Shape shape4;
    private DataDynamics.ActiveReports.TextBox textBox3;
    private DataDynamics.ActiveReports.TextBox txtDIA_HORA_Final1;
    private DataDynamics.ActiveReports.TextBox txtDistancia;
    private DataDynamics.ActiveReports.TextBox txtDIA_HORA1;
    private DataDynamics.ActiveReports.TextBox txtEstado;
    private DataDynamics.ActiveReports.TextBox txtFechaDesde1;
    private DataDynamics.ActiveReports.TextBox txtFechaHasta1;
    private DataDynamics.ActiveReports.TextBox txtIDElemento1;
    private DataDynamics.ActiveReports.TextBox txtIDTransponder1;
    private DataDynamics.ActiveReports.TextBox txtReferenciaCaminos1;
    private DataDynamics.ActiveReports.TextBox txtReferenciaLlegada1;
    private DataDynamics.ActiveReports.TextBox txtReferenciaSalida1;
    private DataDynamics.ActiveReports.TextBox txtTempoTotalTransito;
    private DataDynamics.ActiveReports.TextBox txtTiempoCarga1;
    private DataDynamics.ActiveReports.TextBox txtTiempoDetenido1;
    private DataDynamics.ActiveReports.TextBox txtTiempoTotalCarga;
    private DataDynamics.ActiveReports.TextBox txtTiempoTotalDetenido;
    private DataDynamics.ActiveReports.TextBox txtTiempoTransito1;
    private DataDynamics.ActiveReports.TextBox txtVelocidadDesde1;
    private DataDynamics.ActiveReports.TextBox txtVelocidadHasta1;
    private DataDynamics.ActiveReports.TextBox txtVelocidadMaxima1;
    private DataDynamics.ActiveReports.TextBox txtVelocidadPromedio1;
    internal DataDynamics.ActiveReports.Parameter VelocidadDesde;
    internal DataDynamics.ActiveReports.Parameter VelocidadHasta;
  }
}
